# Generated by Django 4.2.3 on 2023-08-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oduor', '0002_alter_stuffs_youtube_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuffs',
            name='ad',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stuffs',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stuffs',
            name='tutorial_tool',
            field=models.TextField(blank=True),
        ),
    ]
