# Generated by Django 4.2.4 on 2024-01-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oduor', '0005_alter_stuffs_website_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuffs',
            name='website_link',
            field=models.TextField(blank=True, default=''),
        ),
    ]
