# Generated by Django 4.2.4 on 2024-01-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oduor', '0006_alter_stuffs_website_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuffs',
            name='website_link',
            field=models.URLField(blank=True),
        ),
    ]
