# Generated by Django 4.2.2 on 2023-07-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stuffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_tool', models.TextField()),
                ('description', models.TextField()),
                ('tutorial_tool', models.TextField()),
                ('ad', models.TextField()),
                ('youtube_link', models.TextField()),
            ],
        ),
    ]
