# Generated by Django 4.2.3 on 2023-08-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oduor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuffs',
            name='youtube_link',
            field=models.TextField(blank=True),
        ),
    ]
