# Generated by Django 4.2.5 on 2023-12-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oduor', '0003_alter_stuffs_ad_alter_stuffs_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuffs',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
